/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedCareCircleRouteImport } from './routes/_authenticated/care-circle'
import { Route as AuthenticatedCarePlansRouteImport } from './routes/_authenticated/care-plans'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDoctorSummaryRouteImport } from './routes/_authenticated/doctor-summary'
import { Route as AuthenticatedMedicationsRouteImport } from './routes/_authenticated/medications'
import { Route as AuthenticatedMyCareRouteImport } from './routes/_authenticated/my-care'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedSafetyCheckRouteImport } from './routes/_authenticated/safety-check'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedSymptomsIndexRouteImport } from './routes/_authenticated/symptoms.index'
import { Route as AuthenticatedSymptomsNewRouteImport } from './routes/_authenticated/symptoms.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareCircleRoute = AuthenticatedCareCircleRouteImport.update({
  id: '/care-circle',
  path: '/care-circle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarePlansRoute = AuthenticatedCarePlansRouteImport.update({
  id: '/care-plans',
  path: '/care-plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorSummaryRoute =
  AuthenticatedDoctorSummaryRouteImport.update({
    id: '/doctor-summary',
    path: '/doctor-summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicationsRoute =
  AuthenticatedMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyCareRoute = AuthenticatedMyCareRouteImport.update({
  id: '/my-care',
  path: '/my-care',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSafetyCheckRoute =
  AuthenticatedSafetyCheckRouteImport.update({
    id: '/safety-check',
    path: '/safety-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSymptomsIndexRoute =
  AuthenticatedSymptomsIndexRouteImport.update({
    id: '/symptoms/',
    path: '/symptoms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSymptomsNewRoute =
  AuthenticatedSymptomsNewRouteImport.update({
    id: '/symptoms/new',
    path: '/symptoms/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/care-circle': typeof AuthenticatedCareCircleRoute
  '/care-plans': typeof AuthenticatedCarePlansRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctor-summary': typeof AuthenticatedDoctorSummaryRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/my-care': typeof AuthenticatedMyCareRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/safety-check': typeof AuthenticatedSafetyCheckRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/symptoms/new': typeof AuthenticatedSymptomsNewRoute
  '/symptoms/': typeof AuthenticatedSymptomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/care-circle': typeof AuthenticatedCareCircleRoute
  '/care-plans': typeof AuthenticatedCarePlansRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctor-summary': typeof AuthenticatedDoctorSummaryRoute
  '/medications': typeof AuthenticatedMedicationsRoute
  '/my-care': typeof AuthenticatedMyCareRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/safety-check': typeof AuthenticatedSafetyCheckRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/symptoms/new': typeof AuthenticatedSymptomsNewRoute
  '/symptoms': typeof AuthenticatedSymptomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/care-circle': typeof AuthenticatedCareCircleRoute
  '/_authenticated/care-plans': typeof AuthenticatedCarePlansRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctor-summary': typeof AuthenticatedDoctorSummaryRoute
  '/_authenticated/medications': typeof AuthenticatedMedicationsRoute
  '/_authenticated/my-care': typeof AuthenticatedMyCareRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/safety-check': typeof AuthenticatedSafetyCheckRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/symptoms/new': typeof AuthenticatedSymptomsNewRoute
  '/_authenticated/symptoms/': typeof AuthenticatedSymptomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/analysis'
    | '/care-circle'
    | '/care-plans'
    | '/dashboard'
    | '/doctor-summary'
    | '/medications'
    | '/my-care'
    | '/records'
    | '/safety-check'
    | '/settings'
    | '/timeline'
    | '/symptoms/new'
    | '/symptoms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/analysis'
    | '/care-circle'
    | '/care-plans'
    | '/dashboard'
    | '/doctor-summary'
    | '/medications'
    | '/my-care'
    | '/records'
    | '/safety-check'
    | '/settings'
    | '/timeline'
    | '/symptoms/new'
    | '/symptoms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/analysis'
    | '/_authenticated/care-circle'
    | '/_authenticated/care-plans'
    | '/_authenticated/dashboard'
    | '/_authenticated/doctor-summary'
    | '/_authenticated/medications'
    | '/_authenticated/my-care'
    | '/_authenticated/records'
    | '/_authenticated/safety-check'
    | '/_authenticated/settings'
    | '/_authenticated/timeline'
    | '/_authenticated/symptoms/new'
    | '/_authenticated/symptoms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/care-circle': {
      id: '/_authenticated/care-circle'
      path: '/care-circle'
      fullPath: '/care-circle'
      preLoaderRoute: typeof AuthenticatedCareCircleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/care-plans': {
      id: '/_authenticated/care-plans'
      path: '/care-plans'
      fullPath: '/care-plans'
      preLoaderRoute: typeof AuthenticatedCarePlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor-summary': {
      id: '/_authenticated/doctor-summary'
      path: '/doctor-summary'
      fullPath: '/doctor-summary'
      preLoaderRoute: typeof AuthenticatedDoctorSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medications': {
      id: '/_authenticated/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthenticatedMedicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-care': {
      id: '/_authenticated/my-care'
      path: '/my-care'
      fullPath: '/my-care'
      preLoaderRoute: typeof AuthenticatedMyCareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety-check': {
      id: '/_authenticated/safety-check'
      path: '/safety-check'
      fullPath: '/safety-check'
      preLoaderRoute: typeof AuthenticatedSafetyCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/symptoms/': {
      id: '/_authenticated/symptoms/'
      path: '/symptoms'
      fullPath: '/symptoms/'
      preLoaderRoute: typeof AuthenticatedSymptomsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/symptoms/new': {
      id: '/_authenticated/symptoms/new'
      path: '/symptoms/new'
      fullPath: '/symptoms/new'
      preLoaderRoute: typeof AuthenticatedSymptomsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedCareCircleRoute: typeof AuthenticatedCareCircleRoute
  AuthenticatedCarePlansRoute: typeof AuthenticatedCarePlansRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorSummaryRoute: typeof AuthenticatedDoctorSummaryRoute
  AuthenticatedMedicationsRoute: typeof AuthenticatedMedicationsRoute
  AuthenticatedMyCareRoute: typeof AuthenticatedMyCareRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedSafetyCheckRoute: typeof AuthenticatedSafetyCheckRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedSymptomsNewRoute: typeof AuthenticatedSymptomsNewRoute
  AuthenticatedSymptomsIndexRoute: typeof AuthenticatedSymptomsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedCareCircleRoute: AuthenticatedCareCircleRoute,
  AuthenticatedCarePlansRoute: AuthenticatedCarePlansRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorSummaryRoute: AuthenticatedDoctorSummaryRoute,
  AuthenticatedMedicationsRoute: AuthenticatedMedicationsRoute,
  AuthenticatedMyCareRoute: AuthenticatedMyCareRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedSafetyCheckRoute: AuthenticatedSafetyCheckRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedSymptomsNewRoute: AuthenticatedSymptomsNewRoute,
  AuthenticatedSymptomsIndexRoute: AuthenticatedSymptomsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
